
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Session1
{

using System;
    using System.Collections.Generic;
    
public partial class Deals
{

    public int Id { get; set; }

    public int DemandId { get; set; }

    public int SupplyId { get; set; }



    public virtual Demands Demands { get; set; }

    public virtual supplies supplies { get; set; }

}

}
